In [ ]:
import pandas as pd
import random
import numpy as np
from sklearn.model_selection import train_test_split

#1. load the data
df = pd.read_csv("/content/SwikritiKc (2).csv")

#2. Create a new DataFrame by grouping zipcode and aggregating mean, count, sum
zip_agg = (
    df.groupby("zipCode")
     .agg(
        avg_damage=("totalDamage", "mean"),
        count=("totalDamage", "count"),
        total_damage=("totalDamage", "sum")
    )

)

In [ ]:
zip_agg.head()

         avg_damage  count  total_damage
zipCode
23010           0.0      1           0.0
30056           0.0      1           0.0
32018           0.0      1           0.0
32029           0.0      1           0.0
32032           0.0      1           0.0

In [ ]:

#3. Create mock feature: historical_exposure (random integers 1-10)
zip_agg["historical_exposure"] = np.random.randint(1, 11, size = len(zip_agg))

In [ ]:
zip_agg.head()

         avg_damage  count  total_damage  historical_exposure
zipCode
23010           0.0      1           0.0                    4
30056           0.0      1           0.0                    7
32018           0.0      1           0.0                    8
32029           0.0      1           0.0                    2
32032           0.0      1           0.0                    5

In [ ]:
#1. 75th percentile (high-risk threshold) of total_damage
threshold = zip_agg["total_damage"].quantile(0.75)

In [ ]:
# 2. Create Target Variable: high_risk
# If Total Damage >= Threshold, high_risk = 1 (High Risk)
# If Total Damage < Threshold, high_risk = 0 (Low Risk)

zip_agg["high_risk"] = np.where(zip_agg["total_damage"] >= threshold, 1, 0)

In [ ]:
zip_agg.head()

         avg_damage  count  total_damage  historical_exposure  high_risk
zipCode
23010           0.0      1           0.0                    4          0
30056           0.0      1           0.0                    7          0
32018           0.0      1           0.0                    8          0
32029           0.0      1           0.0                    2          0
32032           0.0      1           0.0                    5          0

In [ ]:
# 1. Define X and Y
# Features (X): mean, count, and historical_exposure
X = zip_agg[["avg_damage", "count", "historical_exposure"]]
Y = zip_agg["high_risk"]

In [ ]:
# 2. Train/Test Split (80% train, 20% test)
# Setting random_state=42 ensures the split is the same every time
X_train, X_test, y_train, y_test = train_test_split(
    X,
    Y,
    test_size=0.2,
    random_state=42,
    stratify=Y # Stratify ensures the ratio of 1s and 0s is preserved in both sets
)

print("Data Split Complete!")
print(f"X_train rows: {len(X_train)}")
print(f"X_test rows: {len(X_test)}")

Data Split Complete!
X_train rows: 153
X_test rows: 39

In [ ]:
from google.colab import files

print('Saving data to CSV...')

# Save X_train
X_train.to_csv('X_train.csv', index=False)

# Save X_test
X_test.to_csv('X_test.csv', index=False)

# Convert y_train/y_test from Series to DataFrame for saving
pd.DataFrame(y_train, columns=['high_risk']).to_csv('y_train.csv', index=False)
pd.DataFrame(y_test, columns=['high_risk']).to_csv('y_test.csv', index=False)


# Download all 4 files
files.download('X_train.csv')
files.download('X_test.csv')
files.download('y_train.csv')
files.download('y_test.csv')

print("\n✅ Files saved internally. Now downloading to your computer...")
print("[4 file downloads should happen]")

Saving data to CSV...

✅ Files saved internally. Now downloading to your computer...
[4 file downloads should happen]